name: publish-to-ghcr
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test scenario tags"
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Compose Customized Docker Image"
        run: |
          docker build . --tag ghcr.io/alekslario/rasbign:latest
      - name: "Push the Image"
        run: |
          docker push ghcr.io/alekslario/rasbign:latest
